Refactoring : create meeting
gloddy-dev/gloddy-client pull request #110
Opened 2023-07-14 12:35 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 리팩토링

## 💁 무엇이 어떻게 바뀌나요?

1. 컴포넌트를 다음과 같이 분리하였습니다.

![스크린샷 2023-07-14 오후 9 20 08](https://github.com/gloddy-dev/gloddy-client/assets/62178788/b97cd467-1ad7-46bc-967f-3ddf0f6af6e3)

- page안에는TopNavigationBar와 InputForm으로 구성되어 있습니다. InputForm에는 inputSection폴더의 TitleSection, DescriptionSection, DateSection, LocationSection, NumberSection등으로 구성되어 있습니다.

![스크린샷 2023-07-14 오후 9 22 27](https://github.com/gloddy-dev/gloddy-client/assets/62178788/5941f7a0-c609-4c8b-b96e-0a9373bfb9de)

- 각 컴포넌트는 사진의 각 입력항목을 의미합니다.
- 이 중에서 BottomSheet를 띄우는 DateSection, LocationSection, NumberSection 내부에는 Bottom Sheet또한 포함되어 있습니다. 그래서, 이 3개의 컴포넌트에는 modal관련 props(isModalOpen, openModal, closeModal)를 넘겨줍니다.
- 기존 262줄의 코드였던 `InputForm.client.tsx`를 컴포넌트로 나눔으로써 121줄의 코드로 줄였습니다.

## 💬 리뷰어분들께
자유롭게 해주세용 ~

2023-07-15 05:38 UTC, kangju2000 requested changes
LGTM👍

eslint의 import lint가 적용될 수 있도록 규성님 vscode에 있는 import lint 익스텐션을 끄면 좋을 것 같아요!

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/NumberSection.server.tsx
> +export default function NumberSectionModal({
파일명과 export하는 컴포넌트명이 일치하지 않네요!

`NumberSection`으로 수정하고 import하는 곳에서도 수정 부탁드립니당

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/InputForm.client.tsx
> +      />
각 section 컴포넌트 내부에서 Modal을 따로 관리해줘도 좋을 것 같아요!

지금은 `InputForm` 컴포넌트에서 `useModal` 훅을 통해 여러개의 모달을 관리하고 있는데, 각 섹션 컴포넌트마다 `useModal` 훅을 추가하여 Modal을 관리하는 방향으로 가도 좋을 것 같은데 어떻게 생각하시나요?

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/InputForm.client.tsx
>    const handleSubmitButton = (data: InputType) => {
이 Form 컴포넌트에는 하나의 Submit만 존재하기 때문에 `handleSubmit`으로 핸들러 명을 정하는게 좋아보여요!

```suggestion
  const handleSubmit = (data: InputType) => {
```

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DateSection.server.tsx
> +import TimeSwipePicker from '@/components/common/SwipePicker/TimeSwipePicker';
```suggestion
import { TimeSwipePicker } from '@/components/common/SwipePicker';
```

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DateSection.server.tsx
> +import BottomUpModal from '@/components/common/Modal/BottomUpModal';
```suggestion
import { BottomUpModal } from '@/components/common/Modal';
```

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +import { InputProps } from '@/components/common/Input/TextArea';
```suggestion
import type { InputProps } from '@/components/common/Input/TextArea';
```

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/NumberSection.server.tsx
> +import BottomUpModal from '@/components/common/Modal/BottomUpModal';
```suggestion
import { BottomUpModal } from '@/components/common/Modal';
```

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/NumberSection.server.tsx
> +import InputSection from './InputArea.server';
파일 명과 import하는 모듈 명이 다르네요! 하나로 통일 부탁드려용

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/NumberSection.server.tsx
> +        value={value ? value : ''}
value가 `number` 타입인데 `0`이라면 `string` 타입인  ''가 되는 이유가 있을까요?

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/components/inputSection/TitleSection.server.tsx
> +export default function TitleSection({ ...props }: Omit<InputProps, 'placeholder'>) {
`InputProps`는 input 태그에 들어가는 모든 attribute들이 들어가 있는데, `placeholder`만 Omit하는 이유가 있을까요?

```tsx
<Input placeholder="제목을 입력해주세요" {...props} />
```

`{...props}`를 맨 뒤에 붙인다면 부모 컴포넌트가 placeholder를 입력했을 때 기존의 값이 덮어씌워져서 이렇게 바꾸면 될 것 같아요.

--- 

`TitleSection`은 부모 컴포넌트에서 쓰일 때 section 태그처럼 보여야하는데, 막상 입력할 수 있는 속성은 input 속성들로 이루어져 있어요.

input 속성 대신 `HTMLElement`를 확장해서 section 태그의 속성을 입력할 수 있게끔 하는건 어떨까요?

```tsx
<section {...props}>
```

2023-07-15 05:38 UTC, kangju2000 commented on app/grouping/create/type.ts
> +export type InputType = {
서버에게 전달한 데이터 타입이기 때문에 `InputType`은 너무 넓은 범위인 것 같아요.

`~~RequestType` 이런 식으로 작성하거나 더 좋은 명칭이 있으면 바꿔서 더 명확하게 표현했으면 좋겠어요!

2023-07-15 06:41 UTC, guesung commented on app/grouping/create/components/inputSection/NumberSection.server.tsx
> +        value={value ? value : ''}
value에 0값을 부여하면 그 값(`0`)이 초기값이 되어 입력하기 전에 0이 미리 삽입되어 있었습니다. 미리 삽입되는 것을 방지하기 위해 ''로 부여하도록 하였습니다. 

그런데, value는 number타입이니 값을 부여하지 않기 위해서는 `undefined`가 적절한 초기값 선언인 것 같네요 !

2023-07-15 06:41 UTC, guesung commented on app/grouping/create/components/InputForm.client.tsx
>    const handleSubmitButton = (data: InputType) => {
`handleSubmit`은 `react-hook-form`의 `useModal`훅에서 가져온 함수와 이름이 동일해서 그 부분은 안될 것 같아요 !

2023-07-15 06:41 UTC, guesung commented on app/grouping/create/components/inputSection/TitleSection.server.tsx
> +export default function TitleSection({ ...props }: Omit<InputProps, 'placeholder'>) {
1. `{...props}`를 `<Input>`에 넘기니 기본값이 있다는 이유로 `placeholder`를 굳이 뺄 이유가 없네요. 제외했습니다.
2. 두 번째 사항이 이해가 안되는데, 추가로 설명해주실 수 있나요 ?? 아래와 같은 방식을 말씀하시는건가요 ??
```js
export default function TitleSection({ ...props }: InputProps) {
  return (
    <section {...props}>
      <div className="mb-5 text-14">방 제목</div>
      <Input placeholder="제목을 입력해주세요" {...props} />
    </section>
  );
}
```

2023-07-15 06:49 UTC, guesung commented on app/grouping/create/type.ts
> +export type InputType = {
좋아요 ~

server에 전달할 데이터이기에 `CreateMeetingRequestType`로 설정했습니다 👍

2023-07-15 07:02 UTC, kangju2000 commented on app/grouping/create/components/InputForm.client.tsx
>    const handleSubmitButton = (data: InputType) => {
그러면 저번에 컨벤션 맞춘대로 `handle[~~]Submit`로 하는거 어떤가요?

2023-07-15 07:04 UTC, kangju2000 commented on app/grouping/create/components/inputSection/TitleSection.server.tsx
> +export default function TitleSection({ ...props }: Omit<InputProps, 'placeholder'>) {
> 1. `{...props}`를 `<Input>`에 넘기니 기본값이 있다는 이유로 `placeholder`를 굳이 뺄 이유가 없네요. 제외했습니다.
> 2. 두 번째 사항이 이해가 안되는데, 추가로 설명해주실 수 있나요 ?? 아래와 같은 방식을 말씀하시는건가요 ??
> 
> ```js
> export default function TitleSection({ ...props }: InputProps) {
>   return (
>     <section {...props}>
>       <div className="mb-5 text-14">방 제목</div>
>       <Input placeholder="제목을 입력해주세요" {...props} />
>     </section>
>   );
> }
> ```

넵 제가 방금 해봤을 때는 `{...props}`의 위치에 따라 오버라이딩이 결정이 되는것 같더라구요..

이게 앞에 있으면 부모에서 `placeholder`를 적었을 때 적용이 안됐는데, 뒤에 있으면 기존 placeholder 대신 부모에서 적은 걸로 적용되었습니다!

2023-07-15 07:05 UTC, guesung commented on app/grouping/create/components/InputForm.client.tsx
> +      />
현재 `InputForm`컴포넌트에서 `const { openModal, closeModal, modalName } = useModal<ModalNameType>();` 한 번 useModal을 선언하여, 각 자식 모달 컴포넌트에 함수들을 전달하는 방식으로 관리하고 있습니다.

자식 모달 컴포넌트에서 각각 `useModal`을 사용하여 modal을 관리하면 3개의 modal을 관리해야 하고, 전역 상태 관리를 이용하여 부모 컴포넌트에 다시 올려야 합니다. (다음 모달을 열기, 모달 닫기 등 모달을 컨트롤 해야함)

이 방식은 상당히 번거로움이 있을 것 같습니다.

저번에 주혁님와 이야기를 나누며 했던 이야기 중에, 부모 컴포넌트에서 modal을 관리하되, props로 동일한 값들을 넘기지 않고 전역 상태 관리 라이브러리를 이용하여 modal상태를 관리하는 방식도 괜찮을 거 같아요. 이 방식으로 구현 해볼게요 !

2023-07-15 07:18 UTC, kangju2000 requested changes

2023-07-15 07:18 UTC, kangju2000 commented on app/grouping/create/components/inputSection/InputArea.server.tsx
이 부분도 section 태그로 묶여있는데 `InputSection`에서 `InputArea`로 바꾼 이유를 알 수 있을까요?

2023-07-15 07:18 UTC, kangju2000 commented on components/common/SwipePicker/SwipePicker.tsx
> +      initialSlide={initialValue ? selectList.indexOf(initialValue) : 0}
`selectList.indexOf(initialValue)` 값이 `-1`인 경우일 때는 어떻게 되는 걸까요? 유효하지 않는 값에 대한 에러 처리도 필요해보입니다!

2023-07-15 07:18 UTC, kangju2000 commented on app/grouping/create/components/inputSection/TitleSection.server.tsx
> +    </section>
props가 중복으로 들어가고 있어요!

부모에 input 태그 속성을 전부 입력할 수 있게 하는 이유가 뭘까요? 

필수로 쓰일 값들 (ex. onClick, onChange)만 넘겨줘도 되지 않을까요?

2023-07-15 07:18 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +import { TextareaHTMLAttributes } from 'react';
```suggestion
import type { TextareaHTMLAttributes } from 'react';
```

2023-07-15 07:18 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +}
`Textarea` 속성들을 전부 입력할 수 있게 확장해둔 이유가 있을까요?

필요한 부분만 부모에서 사용할 수 있게 하면 되지 않을까요?

2023-07-15 07:23 UTC, guesung commented on app/grouping/create/components/InputForm.client.tsx
>    const handleSubmitButton = (data: InputType) => {
괜찮은 거 같아요 !

제출하는 값들의 Type명이 `CreateMeetingType`이므로 통일성 있게 `handleCreateMeetingSubmit`로 수정했습니다.

2023-07-15 07:27 UTC, kangju2000 commented on app/grouping/create/components/InputForm.client.tsx
> +      />
> [효율적인 modal 관리](https://nakta.dev/how-to-manage-modals-2) 👍

훅에서 여러개의 모달을 관리하고 있으니 `useModals`라고 바꿔도 좋을 것 같네용

그리고 `BottomUpModal` 중에 뒷 배경 클릭 시 닫히게 하는 기능도 있습니다! 이것도 활용해주면 UX 적으로도 좋아질 것 같아요!

2023-07-15 13:37 UTC, guesung commented on app/grouping/create/components/InputForm.client.tsx
> +      />
글 잘 읽어보았습니다 ! 

글쓴이분은 `Context API`를 이용하여, open/close 함수에 컴포넌트를 인자로 넘겨주면 modals배열에서 늘리거나/빼는 방식으로 구현하였군요 ! 흥미롭네요 😄 

`useModal`훅이 이미 존재하여 이름을 뭐로 해야 하나 고민했었는데 `useModals`괜찮을 것 같네요 !

2023-07-15 13:49 UTC, guesung commented on app/grouping/create/components/inputSection/InputArea.server.tsx
폴더명이 `inputSection`이여서, 컴포넌트명도 `inputSection`이면 혼동이 생길까봐 `inputArea`로 수정했었습니다.

![스크린샷 2023-07-15 오후 10 45 01](https://github.com/gloddy-dev/gloddy-client/assets/62178788/972d7c71-0cc5-4e9a-b761-cbdc5ba19108)

현재 네이밍 기준 위 사진은 `InputArea`이고, `~Section`은 `InputArea`와 `Modal`을 모두 포함한 컴포넌트입니다. Section보다 작은 범위라는 것을 나타내기 위해 Area를 사용하였습니다. 

html 태그 중에 section보다 작은 단위로 쓰이는 article, div, p, span, hear, footer, nav, aside 등이 있으나 이 중에는 다른 적합한 접미사가 없다고 판단하여, Area를 접미사로 사용하였습니다.

2023-07-15 14:09 UTC, guesung commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +}
그렇네요. register외에는 넘겨주는 인자가 없었네요

제거했습니다 !

2023-07-15 14:14 UTC, guesung commented on app/grouping/create/components/inputSection/TitleSection.server.tsx
> +    </section>
확장성을 고려해서 모든 값을 받아서 넘길 수 있는 것 생각했습니다.

그런데 해당 컴포넌트는 공통 컴포넌트가 아닌, `grouping`의 `create`페이지에서만 쓰이는 컴포넌트여서 이러한 점들을 고려하지 않아도 될 것 같네요. 현재, 페이지에서 props로 `register`만 넘기고 있으니 `DescriptionSection`처럼 `register` props만 남기고 제거했습니다.

2023-07-15 14:16 UTC, guesung commented on components/common/SwipePicker/SwipePicker.tsx
> +      initialSlide={initialValue ? selectList.indexOf(initialValue) : 0}
음, 현재 intialValue로 string 혹은 number를 받고 있습니다.

이에 대한 예외처리 하려면 상당히 걸릴 것 같네요.

제가 처음에 `SwipePicker` 컴포넌트를 만들었으나, 그 이후 이전에 계시던 팀원이 수정을 거치면서 코드가 상당히 난잡해졌습니다. 다음 PR에서 해당 컴포넌트에 대한 리팩토링을 진행하며 말씀하신 예외처리 또한 해결하도록 하겠습니다.

2023-07-16 04:14 UTC, kangju2000 requested changes

2023-07-16 04:14 UTC, kangju2000 commented on store/useModals.ts
> +import { ModalNameType } from '@/app/grouping/create/type';
모달을 create 페이지에서만 쓰이는게 아니라서 타입을 좁히면 안될 것 같아요!

그리고 hooks 폴더에 있는 `useModal`을 `useModals`로 변경하고, store의 파일들은 `~~State`로 통일하는 거 어떨까요?
store와 hooks의 구분이 필요해보여요.

`store/useModalsState`
`hooks/useModals`

2023-07-16 04:14 UTC, kangju2000 commented on app/grouping/create/components/inputSection/LocationSection.server.tsx
> +import InputSection from './InputArea.server';
InputArea로 바꿔야해요!

2023-07-16 05:40 UTC, guesung commented on store/useModals.ts
> +import { ModalNameType } from '@/app/grouping/create/type';
여기서 ModalNameType이 
```js
type ModalNameType = 'meetingDate' | 'meetingLocation' | 'meetingNumber';
```
여서, create페이지에서만 종속되는 타입이 맞습니다.

hooks폴더에 있는 `useModal`는 단수로도, 복수로도 쓰이니 `useModals`도 괜찮은 거 같아요. 이제보니, [Zustand 공식 홈페이지](https://github.com/pmndrs/zustand)에서 `use~` 뿐 아니라, `use~Store` 즉 `Store`접미사도 사용하네요. `useModalStore`가 적절한 네이밍인거 같아요 !

2023-07-16 05:42 UTC, guesung commented on store/useModals.ts
> +import { ModalNameType } from '@/app/grouping/create/type';
useJoin의 경우, 회원가입 도메인이므로 다음 PR인 `회원가입 리팩토링`에서 수정하겠습니다 :)

2023-07-16 06:04 UTC, kangju2000 approved these changes

2023-07-16 06:04 UTC, merged