Refactoring : 회원가입 페이지 리팩토링 (컴포넌트 분리)
gloddy-dev/gloddy-client pull request #112
Opened 2023-07-16 13:51 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 리팩토링
- 이슈대응 close #92 

## 💁 무엇이 어떻게 바뀌나요?

### 1. step4페이지를 컴포넌트 분리하였습니다
```js
export default function InputForm() {
  return (
    <div>
      <ImageFrameSection />

      <NicknameSection />

      <Spacing size={10} />

      <BirthdaySection />

      <Spacing size={10} />

      <GenderSection />

      <Spacing size={10} />

      <NextButtonSection />
    </div>
  );
}
```

![스크린샷 2023-07-16 오후 10 41 25](https://github.com/gloddy-dev/gloddy-client/assets/62178788/eabfd66c-fb7e-4f7a-85e6-6b2146289d0b)

- 각 `Section`(ImageFrame, Nickname, Birthday,Gender)은 입력을 받는 input들을 section으로 구분한 것입니다.
- 기존 : 부모 컴포넌트에서 react-hook-form을 이용하여 클라이언트 측에서 상태 관리하다가 -> 다음 페이지로 넘어갈 때 zustand를 이용하여 전역 상태 store에 저장하던 형태에서
- 바뀐 점 : 각 컴포넌트에서 zustand를 이용하여 전역 상태 관리하다가 -> 다음 페이지 넘어갈 때 페이지만 이동하는 형태로 변경하였습니다.
이로써
1. 상태 관리가 간결해지고, 전체 애플리케이션의 복잡성이 줄어들었습니다. 각 컴포넌트가 자신의 상태를 관리하게 되므로, 부모 컴포넌트에서 전체 상태를 관리할 필요가 없어집니다.
2. 컴포넌트 간의 결합도가 줄어들었으며, 이는 코드 유지보수를 더욱 쉽게 만들어 줍니다.
3. 페이지 간 전환 시 필요한 상태만 로드하므로 페이지 로드 시간이 줄어들었습니다.

### 2. 이름 변경
1. `BottomUpModal`이 `BottomSheet`로 변경되었습니다. 이는 해당 컴포넌트의 이름을 보다 일반적으로 사용되는 용어로 명확하게 표현함으로써 이해를 돕습니다.
2. Zustand 스토어의 이름이 `useJoin`에서 `useJoinStore`로 변경되었습니다. 해당 객체가 스토어임을 명시하고, 코드를 읽는 사람이 해당 객체의 용도를 보다 쉽게 파악할 수 있게 합니다. 이렇게 명확한 네이밍은 코드의 가독성을 향상시키고, 유지 보수를 용이하게 합니다.

### 3. flex의 shrink와 grow를 이용한 글자 넘침 해결

이전 코드는 아래와 같습니다.

```js
<div className="relative flex h-52 w-full ... ">
  {label && <p className="flex items-center">{label}</p>}
  <input
    className={clsx(
      'w-full',
      className
    )}
  />
</div>
```
이전에는 `input`이 `w-full`를 가지고 있어, 부모 요소의 가능한 최대 너비로 확장하도록 설정되었습니다. `w-full`, 즉 `width: 100%` 속성은 부모 요소의 너비에 자신의 margin, padding, border를 더한 너비를 가지게 됩니다. 이러한 작동 원리 때문에, `<p>`의 너비가 최소한으로 줄어들게 되었습니다.

그러나, 수정된 코드에서는 다르게 접근했습니다.

```js
<div className="relative flex h-52 w-full ... ">
  {label && <p className="flex items-center">{label}</p>}
  <input
    className={clsx(
      'flex-grow',
      className
    )}
  />
</div>
```
`input` 요소에 `flex-grow` 속성을 추가하여, 사용 가능한 남은 공간을 모두 차지하도록 설정하였습니다. 이로 인해, `<p>` 요소가 최소한의 너비를 가지는 문제가 해결되었습니다.

결론적으로, 사용 가능한 남은 공간을 채울 때는 `w-full`보다 `flex-grow` 속성을 사용하는 것이 더 효과적이라는 것을 알게 되었습니다.

- [참고](https://stackoverflow.com/questions/17468733/difference-between-width-auto-and-width-100-percent)

### 4. 회원가입 페이지에서 부족했던 컴포넌트 분리를 하였습니다.

## 💬 리뷰어분들께

2023-07-17 11:15 UTC, kangju2000 commented on app/grouping/create/components/inputSection/LocationSection.server.tsx
아직까지 eslint import가 각자 다르게 적용되고 있는 것 같네요..? 다음에 `.vscode`에서 해당 import 플러그인을 제거해서 공통된 린트가 동작하도록 설정해야할 것 같습니다!

2023-07-17 11:21 UTC, kangju2000 commented on app/join/step1/components/InputForm.client.tsx
> +        <Spacing size={15} />
18px -> 15px로 스타일이 변경된건가요?

2023-07-17 11:24 UTC, kangju2000 commented on app/join/step2/type.ts
> +};
`InputType`은 너무 큰 범위라고 생각해요.

어떤 Input인지 조금더 구체적인 타입명으로 명시해주면 좋을 것 같아요!

2023-07-17 11:25 UTC, kangju2000 commented on app/join/step3/components/CertificationSection.tsx
> +import { InputType } from '../type';
```suggestion
import type { InputType } from '../type';
```

2023-07-17 11:26 UTC, kangju2000 commented on app/join/step3/components/EmailSection.tsx
> +import { InputType } from '../type';
```suggestion
import type { InputType } from '../type';
```

2023-07-17 11:29 UTC, kangju2000 commented on app/join/step3/components/EmailSection.tsx
> +      >
`float`는 올바르지 않은 클래스인 것 같습니다..!

2023-07-17 11:38 UTC, kangju2000 commented on app/join/step3/components/EmailSection.tsx
> +        <Spacing size={5} direction="horizontal" />
p 태그에서 div 태그를 사용하고 있어서 에러가 나타나고 있어요.

p 태그가 아닌 다른 태그를 사용하는게 좋아보여요!

2023-07-17 11:38 UTC, kangju2000 commented on app/join/step3/components/NoticeSection.tsx
> +      <div className="h-10" />
`Spacing` 컴포넌트를 활용합시당!

2023-07-17 11:39 UTC, kangju2000 commented on app/join/step3/components/NoticeSection.tsx
> +      <div className="h-10" />
위 [코멘트](https://github.com/gloddy-dev/gloddy-client/pull/112#discussion_r1265223376)와 동일!

2023-07-17 11:39 UTC, kangju2000 commented on app/join/step3/type.ts
> +};
위 [코멘트](https://github.com/gloddy-dev/gloddy-client/pull/112#discussion_r1265209060)와 동일!

2023-07-17 11:40 UTC, kangju2000 commented on app/join/step4/components/inputSection/BirthdaySection.tsx
> +import { BirthdayValueType } from '@/types';
```suggestion
import type { BirthdayValueType } from '@/types';
```

2023-07-17 11:47 UTC, kangju2000 commented on app/grouping/create/page.tsx
`InputForm`에서 에러가 터지고 있어요!
`ImageFrame`에서 ref를 상위에서 가져오도록 하고 있는데, 이를 위해서는 `forwardRef`로 가져와야 합니다! [참고 문서](https://www.daleseo.com/react-forward-ref/)

그래서 `ImageFrame` 컴포넌트를 수정해야 할 것 같아용

---

그리고 `ImageFrame` 컴포넌트의 `handleImageInput` 함수에 async/await를 사용하고 있던데 왜 쓴지 알 수 있을까요?

2023-07-17 11:49 UTC, kangju2000 commented on app/join/step4/components/inputSection/ImageFrameSection.tsx
> +import { ImageType } from '@/types';
```suggestion
import type { ImageType } from '@/types';
```

2023-07-17 11:51 UTC, kangju2000 commented on app/join/step4/type.ts
> +import { BirthdayValueType, GenderType, ImageType } from '@/types';
```suggestion
import type { BirthdayValueType, GenderType, ImageType } from '@/types';
```

2023-07-17 11:53 UTC, kangju2000 commented on components/common/BottomFixed/index.tsx
> +  return (
만들어 두었던 `StrictPropsWithChildren`을 사용하는건 어떨까요?

2023-07-17 11:57 UTC, kangju2000 commented on components/common/Input/Input.tsx
rest에서 props로 수정도 부탁드리겠습니다!

2023-07-17 11:58 UTC, kangju2000 commented on components/common/Modal/BottomSheet.tsx
`isModalOpen` 대신 `isOpen`으로 가는건 어떨까요? 그리고 BottomSheet는 모달과는 다른 느낌이 들어서 `BottomSheet` 폴더를 따로 만들어두는건 어떻게 생각하시나용?

2023-07-17 12:02 UTC, kangju2000 commented on store/useJoinStore.ts
> +import { BirthdayValueType, ImageType } from '@/types';
```suggestion
import type { BirthdayValueType, ImageType } from '@/types';
```

2023-07-17 12:05 UTC, kangju2000 commented on store/useJoinStore.ts
`ValueStringType`은 사용하고 있지 않는거 같은데, 남겨두신 이유가 있을까요?

2023-07-17 12:06 UTC, kangju2000 commented on components/common/SwipePicker/GenderSwipePicker.tsx
> +        setValue={setGenderValue}
이 부분에서 타입이 맞지 않은 오류가 뜹니다!

2023-07-17 12:08 UTC, kangju2000 requested changes
고생하셨습니당👍

2023-07-18 03:21 UTC, guesung commented on app/grouping/create/components/inputSection/LocationSection.server.tsx
그러게요 ,, `import` 플러그인 제거 후 다시 적용했습니다 ! 

플러그인이 아직 동작하고 있었네요 😢

2023-07-18 03:22 UTC, guesung commented on app/join/step1/components/InputForm.client.tsx
> +        <Spacing size={15} />
수정을 잘못했네요 😢

2023-07-18 03:32 UTC, guesung commented on app/join/step3/components/EmailSection.tsx
> +      >
`float`가 없어도 `invisible`속성으로 인해 자리 차지를 안하게 되는군요.

2번으로 하게 될 경우 에러가 없을 때는 공간을 차지 안하다가, 에러가 생기면 공간을 차지해 아래 메시지가 밑으로 내려가는 현상이 있습니다.

유저 입장에서 좋지 않은 UX라고 생각하여 1번으로 구현을 하였습니다.

앞으로도 이런 식으로 1번으로 구현하는 것이 좋다고 생각합니다.

2023-07-18 04:32 UTC, guesung commented on store/useJoinStore.ts
타입을 더 세분화해서 따로 쓸 일이 생길 줄 알았는데, 쓸 일이 없네요.

제거했습니다 !

2023-07-18 04:58 UTC, guesung commented on components/common/SwipePicker/GenderSwipePicker.tsx
> +        setValue={setGenderValue}
넵 ! 수정 했습니다.

지금 `SwiperPicker`가 상당히 가독성이나, 유지보수성 측면에서 상당히 좋지 않아보이네요 😢 

1. `setValue에 `kyeType`인자를 무조건 넘겨줘야하는 상황
2. optional props가 많은 상황 : 꼭 넘겨줘야하는 props는 optional을 제거해줘도 될 것 같습니다.

다음 리팩토링 때 꼭 수정해야겠어요.

2023-07-18 05:19 UTC, guesung commented on components/common/Modal/BottomSheet.tsx
`isOpen`으로는 무엇이 열려있는 지 이름만으로  수가 없어 `isOpen`보다는 `isModalOpen`이 더 적합한 네이밍이라고 생각해요.

또한, `BottomSheet`도 기존 화면과 상호작용할 수 없다는 특성을 가지고 있어 [`Modal`의 한 종류](https://yozm.wishket.com/magazine/detail/1272/)입니다. 

`BottomSheet`만을 다른 `Modal`과 구분하게 되면, 현재 존재하는 `ConfirmModal`은 `PopupModal`로, `ModalWrapper`은 `Modal`폴더로 이동하는게 적절하다고 생각합니다. 그렇게 되면 `Modal`이라는 컴포넌트가 여러 폴더에 나뉘게 되어 헷갈릴 수 있을 것 같습니다.

2023-07-18 05:20 UTC, guesung commented on components/common/BottomFixed/index.tsx
> +  return (
더 엄격한 타입 선언 좋아요 👍 

무언가 뒤에 수식어로 붙었으면 좋겠다 생각했는데 `div`괜찮은 거 같네요 !

2023-07-18 06:11 UTC, guesung commented on app/grouping/create/page.tsx
함수형 컴포넌트에 `ref를 전달하기 위해 `forwardRef`함수를 이용해서 ref객체를 가져와야 한다는 것을 깜빡했네요. 수정했습니다 !

2023-07-18 06:12 UTC, guesung commented on app/grouping/create/page.tsx
async/await가 없어도 `URL.createObjectURL`이 정상 동작하는군요. 제거했습니다 !

2023-07-18 06:28 UTC, kangju2000 commented on components/common/Modal/BottomSheet.tsx
바텀시트도 modal의 한 종류였군요? 몰랐네용..ㅎㅎ

근데 `isModalOpen`은 해당 컴포넌트를 사용하는 쪽에서 state 네이밍을 결정하면 되기 때문에 모달 컴포넌트에서는 isOpen으로 두어도 되지 않을까 생각해요! 이미 컴포넌트 이름이 Modal인데 props에서도 Modal이라는 단어가 또 들어가는 느낌이라 저는 살짝 어색해보였습니당 

여는 행위가 컴포넌트 내부에 여러개 있다면 그 때 구체적으로 작성해도 될 것 같은데, 이 부분에 대해서는 어떻게 생각하시나요?

2023-07-18 06:35 UTC, kangju2000 approved these changes

2023-07-18 08:59 UTC, guesung commented on components/common/Modal/BottomSheet.tsx
그게 좋을 거 같네요.

다른 props들을 살펴보니 `modal`을 제외한 `onClose`, `isLeftButton` 등등..이군요. `isModalOpen`또한 `modal`을 제외한 `isOpen`이 적절한 네이밍이라 생각합니다. 👍

2023-07-18 09:01 UTC, merged