Refactoring : 모임 개설 페이지 리팩토링
gloddy-dev/gloddy-client pull request #125
Opened 2023-07-21 06:21 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. 이전에는 'create' 페이지에서 각각의 input 컴포넌트로, 그리고 다시 각각의 input에서 그들의 공통 컴포넌트로 props를 전달해야 하는 두 단계의 props drilling 과정이 필요했습니다. 이런 번거로움을 해결하기 위해, Context API를 사용하여 react-hook-form의 methods들을 각 Input 컴포넌트에 전역적으로 전달하였습니다.
- 결과적으로, InputForm.client.tsx는 높은 수준의 추상화를 가지게 되었으며, 상태 관리는 Provider에서 담당하여 전달하게 되었습니다. 이로써 컴포넌트의 흐름이 간결해지고 유지보수가 용이해졌습니다.

## 💬 리뷰어분들께

2023-07-21 06:43 UTC, kangju2000 requested changes
Context로 묶어서 처리하는 방법 좋은 것 같아요!👍

2023-07-21 06:43 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +        })}
공통 컴포넌트에 `register`라는 props를 받지 않고도 동일하게 구현할 수 있는 방법이 있습니다.

```tsx
<TextArea placeholder="내용을 입력해주세요." {...register('description', { required: true })} />
```

이 방식으로 하고 공통 컴포넌트에 register props 받지 않게 바꾸는게 좋아보입니다!

2023-07-21 06:43 UTC, kangju2000 commented on app/join/step1/page.tsx
> +    <>
저는 page 컴포넌트를 묶기 위해 `<main>` 태그를 쓰고 있는데, main은 어떤가요?

2023-07-21 06:43 UTC, kangju2000 commented on app/grouping/create/components/inputSection/TitleSection.server.tsx
> +      />
이 부분도 `DescriptionSection` 컴포넌트에서 코멘트 단 방식으로 바꾸면 좋겠습니다!

2023-07-21 06:43 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
>          <div className="text-12 text-gray2">0/{TEXT_AREA_COUNT}</div>
입력 시 0이 바뀌는 액션도 있어야 할 것 같아요!

2023-07-21 06:43 UTC, kangju2000 commented on app/grouping/create/components/CreateMettingContext.tsx
`react-hook-form`의 `useFormContext`와 `FormProvider`를 사용하는건 어떨까요? [공식문서](https://react-hook-form.com/docs/useformcontext)

이 메서드로도 똑같이 구현이 가능할 것 같은데, 만약 이 방법으로 사용한다면 `CreateMeetingFormProvider` 라는 커스텀 provider를 만들면 될 것 같네용

---

파일 명 오타 있습니다! Metting -> Meeting

2023-07-21 06:47 UTC, guesung commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +        })}
이런 방식으로 구현해도 되군요 ! 좋아요 :)

2023-07-21 06:48 UTC, guesung commented on app/join/step1/page.tsx
> +    <>
좋아요 ~!

2023-07-21 07:07 UTC, guesung commented on app/grouping/create/components/CreateMettingContext.tsx
처음에 `useFormContext`와 `FormProvider`로 구현을 하였다가, `Context`와 형태가 매우 유사하여 `Context`로 커스텀하여 직접 만들었습니다. 

[react-hook-form github](https://github.com/react-hook-form/react-hook-form/blob/master/src/useFormContext.tsx)에서도 React의 `createContext`를 이용해서 만들었습니다. 

큰 차이가 없다면, 커스텀으로 만든 것이 더 자유도가 높다고 생각합니다.

2023-07-21 07:12 UTC, guesung commented on app/grouping/create/components/CreateMeetingContext.tsx
> +    <CreateMeetingContext.Provider value={contextValue as unknown as UseFormReturn}>
`as unknow as UseFormReturn`은 강제 타입 변환을 수행하는 방식입니다.

이 값이 특정 타입임을 알고 있다고 Typescript에게 알리는 것입니다.

Typescript에서 직접적으로 안전하지 않은 변환이 허용되지 않기 때문에, 먼저 `unknown`으로 타입을 변환하고 그 다음에 원하는 타입(`UseFormReturn`)으로 변환하였습니다.

2023-07-21 07:33 UTC, kangju2000 commented on app/grouping/create/components/CreateMeetingContext.tsx
> +import { createContext, useContext, useMemo } from 'react';
`useMemo`는 사용하고 있지 않는 것 같아 지워주세용

2023-07-21 07:35 UTC, kangju2000 commented on app/grouping/create/components/CreateMeetingContext.tsx
> +export default function CreateMeetingContextProvider({ children }: StrictPropsWithChildren) {
Provider 함수를 default한 이유가 있을까요?

2023-07-21 09:43 UTC, guesung commented on app/grouping/create/components/CreateMeetingContext.tsx
> +export default function CreateMeetingContextProvider({ children }: StrictPropsWithChildren) {
이 컴포넌트가 이 파일의 대표로 export되어지는 컴포넌트라고 생각하여 `export default`하였습니다.

2023-07-22 02:42 UTC, guesung commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +        })}
<img width="740" alt="스크린샷 2023-07-22 오전 11 30 31" src="https://github.com/gloddy-dev/gloddy-client/assets/62178788/6a86bb90-d656-41d7-b1ec-841ae0c038f0">

register를 props로 설정하지 않고 {...register(~)}로 넘겨줄 경우 위 사진과 같은 에러가 발생하였습니다.

이에 register는 props로 명시화하여 props로 child component에 내려주는 것이 올바른 방법인 것 같습니다.

2023-07-22 05:53 UTC, kangju2000 commented on app/grouping/create/components/inputSection/DescriptionSection.server.tsx
> +        })}
> <img alt="스크린샷 2023-07-22 오전 11 30 31" width="740" src="https://user-images.githubusercontent.com/62178788/255307288-6a86bb90-d656-41d7-b1ec-841ae0c038f0.png">
> register를 props로 설정하지 않고 {...register(~)}로 넘겨줄 경우 위 사진과 같은 에러가 발생하였습니다.
> 
> `react-hook-form` 공식 홈페이지에서 제시하는 `register`의 사용법은 다음과 같습니다.
> 
> ```js
> <input defaultValue="test" {...register("example")} />
> ```
> 
> 위와 같은 방법으로 `register`를 `input`에 전달하기 위해서는 register를 props로 Input component에 내려주는 것이 올바른 방법이라 생각합니다.

위 에러는 register에 ref 값까지 받기 때문에 `forwardRef`를 사용하라는 것 같습니다! 그래서 textArea 쪽에서도 ref를 넘겨받을 수 있도록 세팅해두었는데, `register`로 받는 것으로 통일하는게 더 좋겠네요!

그럼 textArea 쪽 ref를 상위에서 받는 부분은 지워도 될 것 같습니다!

2023-07-22 05:55 UTC, kangju2000 approved these changes

2023-07-22 06:31 UTC, merged