Refactoring : 회원가입 페이지 Funnel 형태로 관리하기
gloddy-dev/gloddy-client pull request #135
Opened 2023-07-26 05:13 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. @kangju2000 님이 커스텀하신 `useFunnel`훅을 활용하여 기존 page단위로 넘어가던 회원가입 페이지를 `useFunnel`의 `Funnel.step` 컴포넌트를 교체하는 방식으로 리팩토링하였습니다.
   - 회원가입은 step5페이지에서 한 번 서버에 전송이 이루어집니다. 
   - 하나의 목적, 즉 회원가입을 위한 데이터 전송이라는 하나의 목적을 가진 상태값들인데, 여러 page에 상태가 훝어져있다는 단점이 있었습니다. 그리고, 각 페이지에서 `router.push()`를 이용하여 페이지를 넘겨줘야 했기에 페이지 흐름이 흩어져 있었습니다.
   - 이러한 점들을 `useFunnel`훅을 이용하여 상태값과 페이지의 응집도를 높여주어야겠다고 생각했습니다. 
2. 또한, 기존 코드는 `zustand`와 각 페이지별 `react-hook-form`, `context api`가 상황에 따라 혼합되어 있었습니다. 이러한 형태를 하나로 통일하였습니다. 
    1. 회원가입 페이지의 input 상태값은 `FormProvider`(내부 구조는 `Context API`),로 만든 `JoinContext`
    2. 회원가입 step1~5의 페이지는 `FunnelContext`
    3. 각 페이지별 Modal은 각 페이지 안의 `ModalContext`
    4. 특정 페이지(3페이지)에서만 쓰이는 상태는 `(도메인)Context`
    - 1번의 상태값 관리를 `FormProvider`로 관리하게 될 경우, 한 input값을 바꾸면 다른 form들이 모두 리렌더링이 일어나지 않을까, 하는 고민을 했지만 `react-hook-form`에서 제공하는 [`uncontrolled components`](https://www.react-hook-form.com/faqs/) 특징덕분에 이 고민을 해결할 수 있었습니다.
3. 기존 depth와 구조가 다른 join 각 페이지를 같은 구조로 통일하였습니다.
    - join > page > JoinContextProvider > JoinFunnel > Funnel > Funnel.step > StepNComponent (각 페이지들)
    - 여기서 각 페이지로 들어가면, StepNComponent > UnInteractiveComponents, FormSection, SubmitSection로 구성되어 있습니다. 여기서 UnInteractiveComponents은 말그대로 사용자와 상호작용이 없는 컴포넌트입니다. (e.g. 타이틀, 메시지) 그 외에 FormSection은 사용자들로부터 입력값을 받는 폼, SubmitSection은 제출하는 폼입니다.
    - FormSection과 SubmitSection을 분리하지 않은 페이지도 있는데, 이 페이지들은 화면에서 따로 있지 않고 붙어있는 형태여서 분리할 수 없었습니다.

4. Server component의 Client Component로 변경
    - `Funnel`은 `Context.Provider`로 funnel을 관리하는 형태로, Client에서 상태관리를 하기에 당연히 Client Component입니다. 그래서 자식 요소인 각 페이지별 UnInteractiveComponent(e.g. 타이틀, 메시지) 또한 Client Component로 바뀌었습니다. 
    - Server Component로 할 수 있는 것은 Server Component로 하면 초기 렌더링이 빨라질 것이라 더 좋다고 생각하였으나, `useFunnel`형태로 구현하기 위해서는 어쩔 수 없는 선택이라 생각합니다.

## 💬 리뷰어분들께
- 자유롭게 리뷰해주세용

2023-07-26 16:47 UTC, kangju2000 requested changes
useFunnel을 쓰면서 깔끔해진 것 같네요!👍

다만 한 가지 논의해보아야 할 점이 있습니다.

분리한 컴포넌트들은 외부에서 주입되는 걸 사용하지 않고 컨텍스트를 가져와서 내부적으로 로직을 처리하고 있어요. 이렇게 되면 유지보수성이 더 떨어질 것 같다고 생각이 들었어요.

예를 들면 form 태그 안에 여러 섹션들이 존재할 거예요.

이때 각 섹션 컴포넌트 안에서 context api를 사용해서 처리하는 것이 아닌, form 태그가 적힌 곳에서 controller를 각각 넘겨주어 제어를 부모에서 하는 것이죠. (제어의 역전)

이렇게 되면 섹션 컴포넌트는 어떤 컨트롤러가 들어와도 맞게 대응할 수 있기 때문에 오히려 의존성이 분리되고 재사용에도 용이하게 만들 수 있게 돼요!

이 부분에 대해서는 한 번 의논해보면 좋을 것 같아 코멘트 남깁니당

2023-07-26 16:47 UTC, kangju2000 commented on app/join/funnels/step1/components/NumberForm.tsx
p1)파일이 두개예요! 지워주세요 :)

2023-07-26 16:47 UTC, kangju2000 commented on app/join/funnels/step1/components/NumberVerifyForm.tsx
p1)파일이 두개예요! 지워주세요 :)

2023-07-26 16:47 UTC, kangju2000 commented on app/join/funnels/step2/Step2Component.server.tsx
> +      <SubmitSection />
p4)SubmitSection으로 분리한 이유가 있을까요? Forn 안에 submit button이 있어야할 것 같은데 form과 submit이 따로인 느낌이네요..

그리고 AgreeSection도 폼 필드 값을 들고 있을 것 같은데, 그럼 formSection에 들어가야 하지 않을까요?

2023-07-26 16:47 UTC, kangju2000 commented on app/join/funnels/step3/components/FormSection.client.tsx
여기는 서버 컴포넌트인듯 합니다!

2023-07-26 16:47 UTC, kangju2000 commented on app/join/funnels/step3/Step3Component.server.tsx
> +      </ModalContext>
타이머를 필요한 컴포넌트에서 사용하는 형태가 아닌 context로 뺀 이유가 있을까요?

2023-07-26 16:47 UTC, kangju2000 commented on app/join/funnels/step4/components/FormSection.client.tsx
> +      <GenderForm />
p2)이걸 봤을 때 `이미지, 닉네임, 생일, 성별을 각각 요청하는건가?` 라는 생각이 들었어요.

form 마다 submit이 있다고 생각했는데, 단순히 field만 있는 경우는 네이밍을 다르게 가는게 좋을 것 같아요!

2023-07-26 16:47 UTC, kangju2000 commented on app/join/funnels/step4/components/FormSection.client.tsx
> +      <GenderForm />
추가로, FormSection에서 필드별 controller를 만들어서 props로 보내주도록 하는 건 어떻게 생각하시나요?

이렇게 하면 FormSection에서 봤을 때 각 컴포넌트가 어떤 필드를 사용하고 있는지 한 눈에 볼 수 있을 것 같은데, 이런 방법은 어떤가요?

이번에 올린 [PR](https://github.com/gloddy-dev/gloddy-client/pull/138) body에도 비슷한 내용이 적혀있어서 참고 부탁드립니다!

2023-07-27 02:11 UTC, guesung commented on components/common/Modal/ModalContext.tsx
> +const ModalContext = createContext<ModalContextProps | undefined>(undefined);
그렇군요. 

`null`과 `undefined`를 동일하게 생각하고 있었네요.

추가적으로 `null`은 **의도적으로** 비어있음을 표현하고, `undefined`는 값이 개발자가 의도적으로 할당하기 위한 값이 아니라, JS 엔진이 변수를 초기화할 때 사용하는 값이라고 하네요.

- [참고](https://hanamon.kr/javascript-undefined-null-%EC%B0%A8%EC%9D%B4%EC%A0%90/)

2023-07-27 02:11 UTC, guesung commented on app/join/funnels/step3/Step3Component.server.tsx
> +      </ModalContext>
![image](https://github.com/gloddy-dev/gloddy-client/assets/62178788/34daacf6-f2a9-4784-9d8e-bbc6667121b9)

기획자님에게 여쭤보았을 때, Modal창(이메일 인증창)을 닫고 다시 Modal창을 열었을 경우 time은 유효하게 남아있는 플로우입니다.

time의 경우 Modal창이 닫힌 후에도 남아있어야 해서 FormSection에서는 time을 보여주는 용도로, SubmitSection은 timer를 시작하는 용도로 쓰여야하기에 Context로 뺐습니다.

2023-07-27 02:53 UTC, guesung commented on app/join/funnels/step2/Step2Component.server.tsx
> +      <SubmitSection />
form에 대한 개념을 제가 잘못 생각하고 있었네요.

[form은 `입력된 데이터를 한 번에 서버로 전송`하는 단위](https://www.nextree.co.kr/p8428/)이군요. submit하는 것을 기준으로 form을 나누면 좋을 것 같아요. 

회원가입에서는 휴대전화 인증, 이메일 인증, 회원가입 api 등 서버에 데이터를 전송하는 것을 기준으로 form을 나누고, 한 페이지에 서버에 데이터를 전송하는 버튼이 없다면 한 페이지를 기준으로 form을 나누면 좋을 것 같아요 ! 이 방식대로 구현을 해보겠습니다. 더 좋은 방안 있으면 말씀해주세용 :)

2023-07-27 03:40 UTC, guesung commented on app/join/funnels/step4/components/FormSection.client.tsx
> +      <GenderForm />
흠, 실제로는 하나의 폼인데도 네이밍만 보면 각각 하나의 폼이라고 생각할 수 있겠네요.

각각 Section으로 나누었고, FormSection > InputForm으로 수정하였습니다 😄

2023-07-27 03:44 UTC, guesung commented on app/join/funnels/step4/components/FormSection.client.tsx
> +      <GenderForm />
한 눈에 어떤 필드를 사용하고 있는 지 한 눈에 볼 수 있다면 좋을 것 같아요 !

주혁님이 올리신 PR 리뷰 > 확인 > 머지 후에 저도 반영해볼게요 !

2023-07-27 04:28 UTC, kangju2000 commented on types/index.ts
> +export type GenderType = '남성' | '여성' | '';
젠더 타입은 `남성` `여성` 두개 아닌가요? 빈 스트링을 붙인 이유가 defaultValue 때문이라면, isDirty 같은 formState로 값을 선택했는지 여부를 판단하면 되지 않을까요?

2023-07-27 09:28 UTC, kangju2000 commented on app/join/components/JoinContext.tsx
> +  gender: '',
genderType 에러 뜨고 있습니다!

2023-07-27 09:49 UTC, guesung commented on app/join/components/JoinContext.tsx
> +  gender: '',
@guesung  7f95c7e

2023-07-27 09:50 UTC, guesung commented on app/join/funnels/step5/components/InputForm.client.tsx
> +      <SubmitSection />
7f95c7e

2023-07-27 09:52 UTC, guesung commented on app/join/components/JoinContext.tsx
> +  gender: '',
a0e3c12

2023-07-27 09:52 UTC, guesung commented on app/join/funnels/step5/components/InputForm.client.tsx
> +      <SubmitSection />
e157147

2023-07-27 11:42 UTC, guesung commented on app/join/components/JoinContext.tsx
> +  gender: '',
`GenderType`에 `남성`, `여성` 외에 `선택 없음 타입을 추가하였습니다.

`남성`을 defaultValue로 설정할 경우, 사용자가 성별을 고르지 않고 완료를 누를 경우, default값인 남성이 선택이 됩니다. 그러기 위해서는 사용자가 눌렀는지, 안눌렀느지 `성별` 버튼을 감지 하기 위해 상태값을 하나 추가해야합니다. 

하지만, 이러한 상태값은 `선택없음`이라는 하나의 타입을 추가하면 없어도 되는 상태라 생각하여, `선택없음` 타입을 추가하였습니다.

더 좋은 방법 있으시면 말씀해주세용 !

2507fd5

2023-07-27 14:31 UTC, kangju2000 requested changes

2023-07-27 14:31 UTC, kangju2000 commented on apis/auth/type.ts
> +  gender?: GenderType;
p1)옵셔널 제거해주세용

2023-07-27 14:31 UTC, kangju2000 commented on app/join/components/JoinContext.tsx
> +const defaultValues: SignUpState = {
defaultValues가 이미 타입을 알고 있어서 타입 선언하면 undefined같은거 못하게 됩니다! 여기서는 타입 선언하지 않도록 해주세요
```suggestion
const defaultValues = {
```

2023-07-28 01:50 UTC, guesung commented on app/join/components/JoinContext.tsx
> +const defaultValues: SignUpState = {
d144be6

2023-07-28 02:47 UTC, kangju2000 approved these changes

2023-07-28 02:49 UTC, merged