Refactoring : Swiper Picker 리팩토링 2
gloddy-dev/gloddy-client pull request #143
Opened 2023-07-28 04:18 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 리팩토링

## 💁 무엇이 어떻게 바뀌나요?

1. 스와이퍼를 리팩토링하였습니다.
- Compound Component를 이용하여 `SwipePicker.Bar`와 `SwipePicker.Middle`을 구현하였습니다
- 사용법은 다음과 같습니다.
```js
<SwipePicker.Bar />
<SwipePicker
        selectList={hourList}
        value={timeValue.fromHour}
        setValue={(value: number) => setTimeValue({ ...timeValue, fromHour: value })}
      />
      <SwipePicker.Middle>:</SwipePicker.Middle>
      <SwipePicker
        selectList={minuteList}
        value={timeValue.fromMin}
        setValue={(value: number) => setTimeValue({ ...timeValue, fromMin: value })}
      />
```
- `<SwipePicker.Bar />`는 가운데 회색 영역으로, 한 swiper에 하나만 두면 됩니다.
- 중간에 `:`, `까지`, `부터` 등 메시지를 넣고 싶다면 `<SwipePicker.Middle>`컴포넌트를 사용하면 됩니다.
- 스와이퍼 넘길 때 BottomSheet까지 움직이는 현상이 있어서, `disableDrag`속성을 BottomSheet에 넘겨주었습니다.

## 💬 리뷰어분들께

2023-07-28 04:20 UTC, guesung commented
# 진행 중
1. SwipePicker 타입 에러

2023-07-28 07:39 UTC, kangju2000 requested changes

2023-07-28 07:39 UTC, kangju2000 commented on app/grouping/create/components/CreateGroupContext.tsx
>    },
number 타입으로하면 화면에 보일때 00이 안보이지 않을까요?

2023-07-28 07:39 UTC, kangju2000 commented on components/common/SwipePicker/SwipePicker.tsx
> +function Middle({ children }: StrictPropsWithChildren) {
Middle이 text가 들어가는 컴포넌트인가요?
컴포넌트 명을 좀더 명시적으로 하면 좋을 것 같네요!

그리고 컴파운드 패턴인줄 알았는데 아니었네요..ㅋㅋ

2023-07-28 09:09 UTC, guesung commented on app/grouping/create/components/CreateGroupContext.tsx
>    },
`시간`과 `분`이기에 숫자 타입으로 저장하는 것이 적합하다고 생각하였습니다.

단지 보여주기 위한 것이라면, 값을 보여주는 `SwipePicker`에서 처리해야 하는 역할이라 생각합니다.

2023-07-28 09:10 UTC, guesung commented on app/grouping/create/components/CreateGroupContext.tsx
>    },
4ecebb3

2023-07-28 09:14 UTC, guesung commented on components/common/SwipePicker/SwipePicker.tsx
> +function Middle({ children }: StrictPropsWithChildren) {
f7018c7

`MiddleText`로 수정하였습니다.

2023-07-29 01:25 UTC, guesung commented on components/common/SwipePicker/SwipePicker.tsx
> +                ? '0' + slideContent
996e84b

2023-07-29 01:30 UTC, merged