Featuring : Access Token, Refresh Token 환경 세팅
gloddy-dev/gloddy-client pull request #150
Opened 2023-08-01 00:57 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

### 1. 토큰을 설정하였습니다.
- 토큰을 localStorage에 저장할까 고민을 하다가, localStorage에 저장할 경우 server 에서 데이터를 미리 fetching하는 React server component에서는 사용하지 못한다는 것을 생각했습니다.
- 그래서 cookie에 저장하는 방식으로 구현하였습니다.
1. api를 client와 server, queries를 client와 server로 분리하였습니다.
   - server는 Hydration으로 서버에서 데이터를 미리 받아올 때 사용하는 용도입니다. `privateApi.server`를 사용합니다.
   - client는 client측에서 데이터를 받아올 때 사용하는 용도입니다. `privateApi.client`를 사용합니다.
   - 이에 따라 폴더가 상당히 난잡해졌습니다. 다른 좋은 방법이 있으시면 말씀해주시면 감사하겠습니다.
![스크린샷 2023-08-01 오전 9 45 14](https://github.com/gloddy-dev/gloddy-client/assets/62178788/ee0070c5-b121-45cc-bc79-d0e36c507b42)
   - `groups api`를 예로 들면, `getGroups`는 server측에서 0페이지를 먼저 받아올 수 있고, 무한 스크롤로 구현할 경우 1페이지부터는 client측에서 받아올 수 있습니다. 따라서 client와 server 모두 만들었습니다. 그에 반해 `getGroup`은 server측에서 한 번 받아오면 끝이고, 그 이후 클라이언트에서의 서버와 상호작용은 없습니다. 이에 따라 client에만 만들었습니다. `createGroup`는 post하는 api로, 무조건 client에서 사용하기에 client에만 만들었습니다.

2. groups의 index.ts로 묶어서 export하던 것을 제거하였습니다.
   - index.ts로 export하고, 사용하는 컴포넌트에서 이를 import할 경우 해당 index.ts에서 export한 모든 파일을 가져오게 됩니다. 아래 사진처럼 client 컴포넌트에서 서버 액션을 취할 수 없다는 에러가 발생하였습니다. 이에 따라 index.ts를 제거하였습니다.
![스크린샷 2023-07-31 오후 3.30.51.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/9f41dc9b-679f-4a13-9095-02d518762010/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-07-31_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_3.30.51.png)

3. 토큰 재발급은 아직 미완성입니다. 다음 PR 떄 fix해서 업로드하겠습니다. 토큰 발급은 page.tsx에서 아래 사진과 같은 버튼을 클릭하면 발급받을 수 있습니다. 토큰 재발급이 완성되지 않아, api를 사용할 경우 30분마다 발급받아야 합니다.
![스크린샷 2023-08-01 오전 9 43 51](https://github.com/gloddy-dev/gloddy-client/assets/62178788/c32e1c2c-01d4-4fef-a59a-831220ead3da)

### 2. `layout.tsx` 구조 변경
1. `Layout.tsx`를 만들어 layout 로직을 분리하였습니다.
2. `Provider` > `QueryProvider`로 수정하여 역할을 명시화했습니다.
3. `Layout.tsx`와 `QueryProvider`를 app/components폴더에 넣었습니다.

### 3. GroupingCard 책임 전가
기존 GroupingCard에 props로 내려주던 `router.push`를, GroupingCard안에서 `router.push`함수를 만들도록 수정하였습니다. router.push의 역할은 GroupingCard의 역할이라 생각합니다.

### 4. create 더미데이터 생성
grouping 만드는 더미데이터를 만들었습니다. 서버 측 오류인지, 데이터 타입 오류인지 모르겠으나, 추후에 데이터를 만들 때도 필요할 것이라 생각하여 만들었습니다.
```js

let CREATE_GROUP_DUMMY_DATA: CreateGroupRequest = {
  fileUrl: 'http://example.com/file1.jpg',
  title: 'Group 2',
  content: 'This is another example group',
  maxUser: 30,
  place: 'Busan, South Korea',
  meetDate: '2023-09-02',
  startTime: '18:00',
  endTime: '20:00',
  place_latitude: 35.1796,
  place_longitude: 129.0756,
};
```

## 💬 리뷰어분들께
1. `Provider`는 무조건 client component입니다. 이에 따라 `Provider.client.tsx`로 client/server 컨벤션을 맞추는 것이 어떤 지 의견이 궁금합니다.

2023-08-01 04:47 UTC, kangju2000 requested changes
`next/headers`의 cookies는 서버에서만 사용할 수 있어서 client, server로 분리한 것 같네요!

하지만 이렇게 되면 중복되는 파일들이 너무 많아지고 찾기 힘들 것 같다는 생각이 드네요..

`privateApi` 인스턴스를 하나로 두고, 인터셉터에서 서버인지 아닌지를 판단해서 처리하면 어떨까요?

클라이언트에서 `import { cookies } from 'next/headers'를 하는 것 만으로 에러가 뜨기 때문에 동적으로 임포트하는 식으로 하면 좋지 않을까 합니다!

대충 코드 짜봤는데 이런 식으로 유틸 함수를 만들어서 호출하도록 한다면 privateApi 인스턴스가 하나가 되어 중복 코드가 사라질 것 같습니당


```ts
// getToken.ts
const isServer = typeof window === undefined;

export const getTokens() {
  if(isServer) {
    const { cookies } = await import('next/headers');
    const cookieStore = cookies();
    //...
    return tokens;
  }

  return getAuthTokensByCookie(document.cookie);
}

2023-08-01 04:47 UTC, kangju2000 commented on apis/config/interceptor.client.ts
> +          } else if (validTokenResponse instanceof ApiError) {
else if보다는 그냥 if로 두명 더 깔끔하게 보이지 않을까하는데 어떻게 생각하나요? [stackoverflow](https://stackoverflow.com/questions/20558966/javascript-should-i-write-else-after-if-that-throws-exception)

2023-08-01 04:47 UTC, kangju2000 commented on app/components/Layout.tsx
Layout이 이미 있는데 또 분리한 이유가 있나요?

2023-08-01 04:47 UTC, kangju2000 commented on app/components/QueryProvider.client.tsx
루트 `components` 폴더에 Provider들이 있는데 app쪽으로 뺀 이유가 있을까요?

만약 루트 레이아웃에서 사용하는 목적으로 뺀거라면 `(home)` 폴더를 생성해서 그 안에 컴포넌트 폴더를 생성해서 관리하는건 어떨까요?

2023-08-01 04:47 UTC, kangju2000 commented on app/components/QueryProvider.client.tsx
따로 하고 있는 [프로젝트](https://github.com/kagong-sillok/kagong-sillok-client/tree/develop/src/app/(home))에서도 그루핑해서 관리하고 있습니다!

2023-08-01 04:47 UTC, kangju2000 commented on app/grouping/page.tsx
> +    <HydrationProvider queryKey={Keys.getGroups()} queryFn={getGroupsQuery}>
요렇게 해도 되지 않을까용?
```suggestion
    <HydrationProvider queryKey={Keys.getGroups()} queryFn={() => getGroups(0)}>
```

2023-08-01 04:47 UTC, kangju2000 commented on app/grouping/page.tsx
> +    <HydrationProvider queryKey={Keys.getGroups()} queryFn={getGroupsQuery}>
이렇게 하면 GroupingComponent 비동기 컴포넌트를 만들지 않고 페이지 컴포넌트에 바로 넣어줘도 될 것 같네요

2023-08-01 04:47 UTC, kangju2000 commented on hooks/useUser.ts
> +const GLODDY_RT = 'GLODDY_RT';
상수로 만들었던걸 사용하는건 어떨까요?

2023-08-01 04:47 UTC, kangju2000 commented on hooks/useUser.ts
> +    }) => {
`CookieKeyType` 타입 사용하면 될것 같습니당

2023-08-01 04:47 UTC, kangju2000 commented on utils/auth.ts
> +};
for of 문은 사이드 이펙트가 생길 수 있어 보다 안전한 고차함수를 활용하는게 좋아보여요!

이런 방법은 어떨까요? 더 나은 방법이 있으면 바꿔도 좋을 것 같아용

```suggestion
cookieString.split('; ').forEach((cookie) => {
  const [key, value] = cookie.split('=');
  if (Object.values(AUTH_COOKIE_KEYS).includes(key)) {
    if (key === AUTH_COOKIE_KEYS.userId) {
      cookies[key] = +value;
    } else {
      cookies[key] = value;
    }
  }
});
```

2023-08-01 05:15 UTC, guesung commented on apis/config/type.ts
> +} as const;
327388d

type보다는 `constants`에서 관리하는 것이 맞는 것 같네요 !

2023-08-01 05:18 UTC, guesung commented on apis/config/interceptor.client.ts
> +          } else if (validTokenResponse instanceof ApiError) {
`else if`보다는 `if`가 더 가독성이 좋을 것 같네요 !

앞의 if문(`!validTokenResponse`)과 뒤의 if문(`validTokenResponse instaceof ApiError`)이 곂칠 일도 없으니 제거해도 될 것 같아요 :)

2023-08-01 05:21 UTC, guesung commented on app/components/Layout.tsx
가독성을과 유지보수성을 향상시키기 위해 `layout`속성에 해당하는 요소만을 `Layout.tsx`로 분리하였습니다. 

사이즈나 전체적인 css를 수정하고 싶을 때 `layout.tsx`이 아니라 `Layout.tsx`만을 수정하면 됩니다.

2023-08-01 05:34 UTC, guesung commented on app/components/QueryProvider.client.tsx
[Route Groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups#organize-routes-without-affecting-the-url-path)방식은 URL path에 영향을 끼치지 않기 위해서 사용하는 방식으로 알고 있습니다

(home)으로 묶는 것은 `layout.tsx`에 들어가는 컴포넌트와는 관계가 없는 것 같습니다.

2023-08-01 05:35 UTC, guesung commented on app/grouping/page.tsx
> +    <HydrationProvider queryKey={Keys.getGroups()} queryFn={getGroupsQuery}>
간결하고 좋네요 !

2023-08-01 05:41 UTC, guesung commented on hooks/useUser.ts
> +const GLODDY_RT = 'GLODDY_RT';
중복되군요. 좋아요 !

0808633

2023-08-01 05:41 UTC, guesung commented on hooks/useUser.ts
> +    }) => {
c955df4

2023-08-01 06:41 UTC, kangju2000 commented on app/components/Layout.tsx
Layout 컴포넌트를 다른 곳에서도 사용하는 경우가 없을 것 같은데 유지보수성이 좋아진다고 생각하는 이유가 있을까요?

2023-08-01 06:42 UTC, guesung commented on utils/auth.ts
> +};
`for of`문은 Javascript에서 배열을 순회하는 가장 강력한 방법으로, `for/in`, `for`, `forEach`보다 더 많은 장점을 가지고 있습니다. 

1. [await를 사용한 `for-await-of`](https://exploringjs.com/impatient-js/ch_async-iteration.html#for-await-of)
2. `break`, `continue`사용

for/of문은 forEach과 달리 반복을 중단을 할 수 있다는 점이 있지만, 이러한 점이 이 상황에서 사이드 이펙트를 일으킬 수 없다고 생각합니다.

어떤 점에서 사이드 이펙트가 일어날 수 있다고 생각하셨는 지 궁금합니다.

- [참고 : thecodebabarian blog](https://thecodebarbarian.com/for-vs-for-each-vs-for-in-vs-for-of-in-javascript.html)

2023-08-01 06:53 UTC, kangju2000 commented on app/components/QueryProvider.client.tsx
`app/components` 폴더로 작성하게 되면 모르는 사람이 봤을 때 페이지로 보일 것 같은데, 만약 루트 페이지에서만 사용하는 hook이나 constant가 추가로 필요해서 폴더를 생성하게 되면 페이지와 구분되지 않게 될 것을 우려했어요.

[관련 stackoverflow](https://stackoverflow.com/questions/76156128/nextjs-13-app-directory-how-to-specify-a-route-folder-for-the-home-page)

루트 페이지만의 레이아웃이 필요한 경우, layout 파일을 두개 생성할 수가 없지만, `(home)` 폴더로 그루핑한다면 자체 layout을 설정하게 할 수 있게 됩니다. 또한 루트 페이지 관련 폴더들도 한 곳에 저장할 수 있어 관리하게 좋다고 생각합니다.

2023-08-01 06:53 UTC, kangju2000 commented on app/components/QueryProvider.client.tsx
루트 layout 컴포넌트에 들어가는 파일들은 공통으로 들어가게 되기 때문에 의미상 `src/components` 안에 들어가는게 좋을 것 같은데 어떻게생각하시나요?

2023-08-01 08:03 UTC, guesung commented on app/components/QueryProvider.client.tsx
저희가 현재 도메인에 종속되는 `components`를 각 도메인 폴더 별로 만들어서 사용하기에 app/components에 app/layout.tsx에서만 사용되는 컴포넌트를 넣은 것입니다.

하지만 주혁님의 이야기를 듣고 루트 페이지에 종속되는 것이 아니라, `layout.tsx`에서만 사용하는 컴포넌트기에 app/components폴더는 옳지 않은 방식이라는 생각을 했습니다.

또한, 특정 도메인이 아니라 `layout.tsx`에서 사용하는 컴포넌트이기에 route groups 방식은 부적합하다고 생각합니다.

주혁님 말씀대로 `src/components` 폴더 안에 들어가는 것이 좋을 것 같습니다.

2023-08-02 08:39 UTC, kangju2000 approved these changes

2023-08-02 08:40 UTC, merged