Setting : Eslint, Prettier Github Action 자동화
gloddy-dev/gloddy-client pull request #156
Opened 2023-08-04 00:08 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. Github Action을 이용하여 Eslint와 Prettier를 자동화하였습니다. 

## 💬 리뷰어분들께

2023-08-04 00:08 UTC, guesung commented
# 적용되는 지 Test 중

2023-08-04 04:26 UTC, kangju2000 requested changes

2023-08-04 04:26 UTC, kangju2000 commented on .prettierrc.js
> +};
테윌윈드 플러그인 지운 이유가 있을까요?

2023-08-04 05:48 UTC, guesung commented on .prettierrc.js
> +};
prettier에서 에러를 출력하였습니다.

이 코드를 제거해도 정상 동작해서 제거했습니다.

`tailwind.config.js`에서 아래 코드로 prettier적용이 되는 듯합니다.
```js
  plugins: [require('prettier-plugin-tailwindcss')],
```

2023-08-04 10:40 UTC, kangju2000 commented on .prettierrc.js
> +};
제쪽에서 테스트해보았을때는 적용되지 않습니다. 해당 플러그인은 prettier용 플러그인이라 tailwindcss 설정 파일에 적용하면 안되는 것으로 알고 있는데 혹시 어떤 에러가 띄워졌나요?

2023-08-04 11:00 UTC, guesung commented on .prettierrc.js
> +};
다시 해보니 에러가 뜨지 않네요.

코드 다시 추가했습니다 !

045bf67

2023-08-05 03:20 UTC, kangju2000 approved these changes

2023-08-05 03:41 UTC, merged