Featuring : Reissue 로직 수정
gloddy-dev/gloddy-client pull request #162
Opened 2023-08-06 09:30 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. 기존 privateApi의 intercetor.response에서 토큰을 재발급하여 쿠키에 설정하는 과정에서 아래와 같은 에러가 발생했습니다.
![image](https://github.com/gloddy-dev/gloddy-client/assets/62178788/fb9dbd2f-fb9e-4297-914b-98b0c3e0f8a3)
- 이는 `cookies`를 이용한 쿠키 수정은 [Server Action 혹은 Route Handler](https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options)에서만 사용 가능하기기때문에 발생하던 이슈였습니다.
- 이에 따라 middleware에서 쿠키를 체크하고 설정하였습니다.
- matcher로 설정한 `'/grouping', '/meeting', '/profile'`페이지에서만 토큰 확인이 일어납니다.
- 현재는 expire 기간을 설정하지 않아서 매 번 토큰 재발급이 일어납니다. 추후 리팩토링 때 expire 쿠키를 설정하며 access token의 expire 기간(1시간)이 만료되면 토큰을 재발급하도록 수정하겠습니다.

## 💬 리뷰어분들께

2023-08-06 09:43 UTC, kangju2000 reviewed
👍👍

2023-08-06 09:43 UTC, kangju2000 commented on apis/config/publicFetch.ts
> +class PublicFetch {
지금은 PrivateFetch가 PublicFetch를 extends하고 있는데 잘못 확장한 것처럼 보이네용..

BaseFetch로 바꾸고 PublicFetch과 PrivateFetch 클래스에 BaseFetch를 extends하는 방식은 어떨까요?

2023-08-06 09:43 UTC, kangju2000 commented on apis/config/privateFetch.ts
> +export { PrivateFetch, privateFetch };
클래스와 인스턴스를 둘다 export하는 이유가 있을까용?

2023-08-06 09:43 UTC, kangju2000 commented on apis/config/privateApi.ts
안쓰는 import 지워주세용~!

2023-08-06 09:43 UTC, kangju2000 commented on apis/config/privateFetch.ts
기존에 있던 `privateApi` 대신 `privateFetch`와 `publicFetch`를 사용하는 상황은 언제인가요?

2023-08-06 09:50 UTC, guesung commented on apis/config/privateApi.ts
97f01e0

2023-08-06 09:52 UTC, kangju2000 commented on apis/config/privateApi.ts
`privateApi` 파일에도 있어용

2023-08-06 09:57 UTC, guesung commented on apis/config/privateFetch.ts
middleware.ts에서는 axios를 사용하지 못합니다.

https://stackoverflow.com/questions/75280544/uncaught-in-promise-error-error-adapter-http-is-not-available-in-the-build

그래서 `middleware.ts`에서 한정적으로 fetch api를 custom하여 사용하였습니다.

이렇게 axios를 사용하지 못하여 불가피하게 fetch를 사용하게 될 때 사용하면 될 것 같습니다.

또한 privateFetch는 access token을 headers에 담아서 보낼 때, publicFetch는 담지 않을 때 사용합니다.

2023-08-06 10:00 UTC, guesung commented on apis/config/privateFetch.ts
> +export { PrivateFetch, privateFetch };
둘 다 fetch할 필요가 없겠네요. 수정했습니다 !

c2da802

2023-08-06 11:57 UTC, guesung commented on apis/config/privateApi.ts
31b5a96

2023-08-06 12:16 UTC, guesung commented on apis/config/publicFetch.ts
> +class PublicFetch {
publicFetch와 privateFetch의 `put`, `post`에 대한 선언 등 중복되는 코드를 제거해도 될 것 같네요 !

privateFetch가 privateFetch와 다른 점이 token을 담느냐 안담느냐 뿐이여서 privateFetch는 publicFetch를 확장하면 좋을 것 같아요 !

2023-08-06 12:20 UTC, guesung commented on apis/config/publicFetch.ts
> +class PublicFetch {
f2f10aa

2023-08-07 00:11 UTC, guesung commented on apis/config/publicFetch.ts
> +class PublicFetch {
상속은 `is-a`관계여야 하는데 제가 상속을 잘못 활용하고 있었네요.

추가적으로, `middleware.ts`에서 실행한 fetch에서 cookie에 접근하지 못하는 현상이 있었습니다.

그래서 `middleware.ts`에서 직접 headers에 토큰을 담아서 전송했습니다.

`axios`를 이용하지 build과정에서 사용되는 api에서는 cookie에 접근을 하지 못하니 cookie에서 꺼내서 건내줘야합니다.

그래서 privateFetch와 publicFetch를 구분할 필요가 없다고 생각하여, `baseFetch`로 통일하겠습니다.

2023-08-07 00:12 UTC, guesung commented on apis/config/publicFetch.ts
> +class PublicFetch {
아직 그럴 일이 없을 것이라 예상하지만, 추후에 fetch를 이용해야 할 때 token을 cookie에서 꺼내서 전송하는 api가 여럿 생긴다면 그 때 privateApi로 구분하여도 될 것 같습니다.

2023-08-07 04:27 UTC, kangju2000 requested changes

2023-08-07 04:27 UTC, kangju2000 commented on .gitignore
env 뺀 이유가 있을까요? 위험할것 같습니당

2023-08-07 06:08 UTC, guesung commented on .gitignore
7b2bc4e

2023-08-07 06:09 UTC, guesung commented on .gitignore
실수로 뻈네용 ..!

다시 추가했습니다

2023-08-07 15:06 UTC, kangju2000 approved these changes

2023-08-07 15:07 UTC, merged