Component : Popup 컴포넌트
gloddy-dev/gloddy-client pull request #212
Opened 2023-08-15 01:15 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. Popup 컴포넌트를 구현하였습니다.
![스크린샷 2023-08-15 오전 10 15 02](https://github.com/gloddy-dev/gloddy-client/assets/62178788/cecc5a19-3fa2-4290-8f21-fe804820b46e)
    - vscode에서 확인하려면 grouping/create페이지에서 `GroupingPopup` 주석 해제하시고 확인해주시면 됩니다.

## 💬 리뷰어분들께

2023-08-15 05:28 UTC, kangju2000 requested changes
create 페이지에서 테스트해보았을 때 헤더의 우선순위가 더 높아서 가려집니다!

팝업의 z-index를 더 높게 잡아야 할 것 같아용~

우선순위가 많아지면 관리하기 힘들어서 상수로 관리해도 좋을 것 같네요!

<img width="521" alt="image" src="https://github.com/gloddy-dev/gloddy-client/assets/23312485/1ac5f4ca-442f-49f2-a9b2-1f651c1a7b5d">

### 에러

이 에러도 수정해주시면 감사하겠습니다!

<img width="524" alt="image" src="https://github.com/gloddy-dev/gloddy-client/assets/23312485/d210dfb0-c4e2-4fba-b480-e61414702a09">

2023-08-15 05:28 UTC, kangju2000 commented on src/components/Modal/ModalContext.tsx
상단에 use client와 파일 명 수정해주세요!

2023-08-15 05:28 UTC, kangju2000 commented on src/components/Modal/Popup.client.tsx
> +  children?: React.ReactNode;
StrictPropsWithChildren이 children 넣어주고 있어서 이부분은 빼도 좋을 것 같아요!

2023-08-15 05:28 UTC, kangju2000 commented on src/components/Modal/Popup.client.tsx
> +        {variant && (
variant는 디폴트로 `warning`이 들어가는데 이 분기 처리는 의미가 없어보이네용

2023-08-15 05:28 UTC, kangju2000 commented on src/components/Modal/Popup.client.tsx
> +            </Button>
버튼이 하나만 있는 경우는 어떻게 해야할까요?

2023-08-15 05:28 UTC, kangju2000 commented on src/components/Modal/ModalWrapper.tsx
p1)훅을 호출하고 있어서 이거도 client로 바꿔주세요!

그리고 motion 쓰는 곳은 use client를 달아야하는 걸로 알고 있습니다! 내부적으로 Context를 가지고 있어서 그런 것 같아요

2023-08-15 05:28 UTC, kangju2000 commented on src/components/Modal/ModalWrapper.tsx
> +        <div className="fixed left-1/2 top-0 z-10 h-full w-full max-w-450 -translate-x-1/2 bg-[rgba(0,0,0,0.4)]">
motion.div에 스타일을 주지 않고 div를 추가해서 따로 준 이유가 있을까요?

2023-08-15 12:59 UTC, kangju2000 commented on src/app/grouping/create/components/GroupingPopup.client.tsx
파일명 popup 대신 modal로 수정해주세요!

2023-08-15 12:59 UTC, kangju2000 commented on src/components/Modal/ModalContext.tsx
파일명 client로 수정해주세요! common 쪽 Modal 폴더에 있는 파일을 변경한것 같습니다

2023-08-15 12:59 UTC, kangju2000 commented on src/components/Modal/index.ts
ModalContext 추가하고 import한 곳 수정 부탁드립니다!

2023-08-16 02:51 UTC, guesung commented on src/components/Modal/ModalWrapper.tsx
a6f7453

2023-08-16 02:54 UTC, guesung commented on src/components/Modal/index.ts
추가했습니다 👍 

7bd5b99

2023-08-16 02:54 UTC, guesung commented on src/components/Modal/ModalContext.tsx
그렇네요 ㅜ common은 이제 사용안하니 제거해야겠어요 

d190472

2023-08-16 09:13 UTC, kangju2000 approved these changes

2023-08-16 10:05 UTC, merged