Feature : Grouping Card 컴포넌트 구현
gloddy-dev/gloddy-client pull request #225
Opened 2023-08-17 09:26 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. Grouping Card 컴포넌트를 구현하였습니다.
![스크린샷 2023-08-17 오후 6 26 09](https://github.com/gloddy-dev/gloddy-client/assets/62178788/238fb45e-48f0-4fe2-a871-fc529aeb90d1)

## 💬 리뷰어분들께

2023-08-17 18:40 UTC, kangju2000 requested changes
저희 text 기본 색이 layout에 아직 반영되어있지 않아서 text-sign-primary를 layout 쪽에 디폴트로 두는건 어떨까요?

2023-08-17 18:40 UTC, kangju2000 commented on src/components/Header/Header.server.tsx
> +import { HtmlHTMLAttributes, PropsWithChildren } from 'react';
type 추가해주세용

2023-08-17 18:40 UTC, kangju2000 commented on src/components/Header/Header.server.tsx
파일명을 Header.tsx로 바꿔야 할 것 같습니당!

header에 들어가는 text에 서버에서 가져온 text를 넣어야 하는 경우에는 server component로 둘 수 없게 돼요.

서버 컴포넌트로 살려둘려고 text를 ReactNode로 바꾼 후 Suspense 걸어서 처리해봤는데 제목이 안뜨다가 나중에 뜨니까 안 예쁘더라구요..ㅋㅋ 

모임 상세 페이지에서는 요청이 모두 완료되었을 때 한번에 띄우는게 더 좋아보이기도 해서 Header를 클라이언트 컴포넌트로 두어 처리하고 있습니다!

2023-08-17 18:40 UTC, kangju2000 commented on src/components/Header/Header.server.tsx
> +Header.Right = Right;
오오 분리했네용 👍👍

추가로 `leftNode`, `rightNode` 이제 사용하지 않는 prop이라 지워도 될 것 같아요!

+) text까지!

2023-08-17 18:40 UTC, kangju2000 commented on src/app/grouping/components/GroupingCard.client.tsx
> +        </p>
아이콘과 글자 사이 4px 추가해주세요!

2023-08-17 18:40 UTC, kangju2000 commented on src/app/grouping/components/GroupingCard.client.tsx
> +        <p className="w-250 truncate text-paragraph-2">{content}</p>
글자 색 추가해주세요!

2023-08-17 18:40 UTC, kangju2000 commented on src/components/Badge/Badge.tsx
이 컴포넌트는 활용하고 있는 컴포넌트가 아닌 것 같은데 사용할 수 있는 건가요?

2023-08-18 01:11 UTC, guesung commented on src/components/Header/Header.server.tsx
> +Header.Right = Right;
분리하니까 확실히 가독성이 좋은 것 같아요.

아직 leftNode, rightNode를 사용하는 컴포넌트가 있어서, 점진적으로 리팩토링하는 곳에서 Left,Right를 사용하는 방식으로 교체해나가는 방식이 어떤가요 !

2023-08-18 01:12 UTC, guesung commented on src/components/Header/Header.server.tsx
> +import { HtmlHTMLAttributes, PropsWithChildren } from 'react';
396ad05

2023-08-18 01:14 UTC, guesung commented on src/components/Header/Header.server.tsx
3476498

그렇군요. server component로 사용 가능한 곳은 server component, 아닌 곳은 client component 유동적으로 사용하는 것이 좋겠네요. 

서버 컴포넌트와 클라이언트 컴포넌트 모두에서 사용할 수 있으니 `Header.tsx`로 수정했습니다 👍

2023-08-18 01:16 UTC, guesung commented on src/app/grouping/components/GroupingCard.client.tsx
> +        </p>
ca6eecf

꼼꼼하십니다 👍 👍

2023-08-18 01:18 UTC, guesung commented on src/components/Badge/Badge.tsx
42670f6

앗 아닙니다. 제거했습니다 ! 👍

2023-08-18 06:17 UTC, kangju2000 approved these changes

2023-08-18 06:21 UTC, merged