Page : 프로필 수정 페이지 구현
gloddy-dev/gloddy-client pull request #260
Opened 2023-08-24 03:09 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. 프로필 수정 페이지를 구현하였습니다.
![Screenshot 2023-08-24 at 12 07 17 PM](https://github.com/gloddy-dev/gloddy-client/assets/62178788/3d9c7025-3483-4b4e-8c90-8a0f26f45907)

## 💬 리뷰어분들께

2023-08-24 12:42 UTC, kangju2000 requested changes

2023-08-24 12:42 UTC, kangju2000 commented on src/components/Tag/Tag.tsx
수정 페이지에서의 Tag는 outline이 없어야 되는데 variant가 outline이 기본이라 solid일 때 outline이 안 보이게 수정해야 할 것 같습니다!

그리고 디자인 시스템 상에서는 Tag를 활용하지 않고 badge라는 컴포넌트를 따로 만들어서 사용하고 있는 것 같습니다..!

2023-08-24 12:42 UTC, kangju2000 commented on src/app/(main)/profile/setting/edit/components/InputForm.client.tsx
> +      <ImageFrame setImageUrl={(imageUrl: string) => setValue('imageUrl', imageUrl)} />
요기는 나중에 useFileUpload 훅 머지 되면 Avatar 활용해서 구현해주세요!

2023-08-24 12:42 UTC, kangju2000 approved these changes

2023-08-27 00:05 UTC, guesung commented on src/components/Tag/Tag.tsx
1fb2993

outline이 없는 solid 컴포넌트인구요. 추가하고 수정했습니다 👍

2023-08-27 00:06 UTC, merged