Feature : 그루핑 페이지 무한 스크롤링 구현
gloddy-dev/gloddy-client pull request #337
Opened 2023-09-02 12:08 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. 무한 스크롤 훅을 구현하였습니다.
사용법은 다음과 같습니다.
```js
const { data, fetchNextPage } = useGetGroups();
const target = useIntersection(fetchNextPage);
```
```js
export const useGetGroups = () => {
  const { data, ...rest } = useSuspenseInfiniteQuery(
    Keys.getGroups(),
    ({ pageParam = 0 }) => getGroups(pageParam),
    {
      getNextPageParam: (lastPage) => lastPage.currentPage + 1,
    }
  );
  return {
    data: data.pages?.flatMap((page) => page.contents),
    ...rest,
  };
};
```
3. 그루핑 페이지 무한 스크롤링 구현하였습니다.

## 💬 리뷰어분들께

2023-09-02 12:38 UTC, kangju2000 requested changes

2023-09-02 12:38 UTC, kangju2000 commented on src/hooks/useInfinityQuery.ts
이 훅의 이름이 리액트 쿼리 훅과 비슷하기도 하고 의미가 불분명한 것 같습니다..!

useIntersect 같은 이름으로 변경하는건 어떨까요?

2023-09-02 12:38 UTC, kangju2000 commented on src/hooks/useInfinityQuery.ts
> +  ) => Promise<InfiniteQueryObserverResult<GroupsResponse, unknown>>,
훅 안에 특정 리스폰스 타입이 들어가고 있는데 제거 부탁드려요!

2023-09-02 14:08 UTC, guesung commented on src/hooks/useInfinityQuery.ts
헷갈릴 수 있겠네요. 좋아요 !

2023-09-02 17:39 UTC, kangju2000 requested changes
페이지 끝으로 가면 계속 추가 페이지를 요청하게 되네요..!

`useGetGroups` 에서 아래와 같이 수정부탁드립니다! 근데 이렇게 바꿔도 맨 아래로 스크롤했을 때 재렌더링이 계속되네요.. 확인해주시면 감사하겠습니다!

```ts
getNextPageParam: (lastPage) => { 
  lastPage.totalPage !== lastPage.currentPage ? 
    lastPage.currentPage + 1 
    : undefined,
}
```

2023-09-02 17:39 UTC, kangju2000 commented on src/hooks/useInfinityQuery.ts
@guesung 파일명도 수정 부탁드려요!

2023-09-03 03:36 UTC, kangju2000 approved these changes
👍

2023-09-03 05:32 UTC, merged