Feature : Modal 페이지 처리
gloddy-dev/gloddy-client pull request #392
Opened 2023-09-06 11:33 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처
- close #390 

## 💁 무엇이 어떻게 바뀌나요?

1. Modal / BottomSheet띄어질 경우 페이지가 바뀌도록 구현하였습니다.

## 💬 리뷰어분들께

2023-09-07 10:33 UTC, kangju2000 requested changes
조금만 고치면 구현될 것 같네요!! 좋습니다 👍

2023-09-07 10:33 UTC, kangju2000 commented on src/components/Modal/Modal.client.tsx
> +  let isGoBackClicked = false;
state 대신에 일반 변수로 처리하지 않은 이유가 있을까요?

2023-09-07 10:33 UTC, kangju2000 commented on src/components/Modal/BottomSheet.client.tsx
> +    history.pushState({ page: 'modal' }, document.title);
바텀시트랑 모달이랑 같이 키는 경우가 있는데, 이때 한 모달을 끄면 다 같이 꺼지게 되는것 같아요!(게시글 더보기버튼)
 확인 부탁드려용

2023-09-08 06:09 UTC, guesung commented on src/components/Modal/Modal.client.tsx
> +  let isGoBackClicked = false;
현재 로직은, Modal/BottomSheet가 mount될 때 `isGoBackClicked`을 false로 초기화하고, unmount될 때 true로 만드는 방식입니다. 이미 true가 되었을 경우, 이미 뒤로가기를 했다는 의미이므로 back()을 실행하지 않습니다.

state로 관리할 경우, useEffect를 이용한 lifecycle을 이용하지 못합니다.

또한, 일반 값으로 관리할 경우, 리렌더링이 일어나면 상태값을 잃게되므로 `useRef()`로 관리하는 로직으로 수정하였습니다.

2023-09-08 06:12 UTC, guesung commented on src/components/Modal/BottomSheet.client.tsx
> +    history.pushState({ page: 'modal' }, document.title);
계속 시도해봤는데, modal에서 뒤로가기를 누르면 이를 bottomsheet에서 추가한 이벤트(popstate 이벤트)도 감지를 해서 함께 동작하네요. 이는 로직을 수정하던지, 방법을 고민해봐야할 것 같습니다 ㅜㅜ

2023-09-08 07:36 UTC, kangju2000 commented on src/components/Modal/BottomSheet.client.tsx
> +    history.pushState({ page: 'modal' }, document.title);
모달과 바텀시트의 page 값을 다르게 하거나 사용하는 쪽에서 page 값을 결정하도록 하면 어떻게되는지 확인할 수 있을까용?

2024-03-19 05:17 UTC, closed without merging