Feature : login 페이지 자동 로그인으로 구현
gloddy-dev/gloddy-client pull request #429
Opened 2023-09-12 14:53 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 신규 피처

## 💁 무엇이 어떻게 바뀌나요?

1. login 페이지를 자동 로그인으로 구현하였습니다.

## 💬 리뷰어분들께

2023-09-12 18:25 UTC, kangju2000 requested changes

2023-09-12 18:25 UTC, kangju2000 commented on src/app/[lng]/(sub)/login/Login.tsx
> +    router.push('/grouping');
`/grouping`으로 바로가면 미들웨어의 postReissue에서 에러 터져서 join으로 넘어가더라구요..

`/`로 바꾸면 해결되긴 하는데 원인 파악하고 추후에 미들웨어 리팩토링이 필요해보입니다!

2023-09-13 06:22 UTC, kangju2000 approved these changes
👍

2023-09-13 06:23 UTC, guesung commented on src/app/[lng]/(sub)/login/Login.tsx
> +    router.push('/grouping');
확인했습니다 ~! 👍

2023-09-13 06:23 UTC, merged