Refactoring : Client Component - Server Component 분리
gloddy-dev/gloddy-client pull request #90
Opened 2023-07-08 09:31 UTC by guesung

## 💡 왜 PR을 올렸나요?

- 리팩토링

## 💁 무엇이 어떻게 바뀌나요?
<img width="396" alt="스크린샷 2023-07-08 오후 6 26 21" src="https://github.com/gloddy-dev/gloddy-client/assets/62178788/c0167833-bc58-4191-b93b-75522f0bb74d">

1. 위 사진과 같이 상태관리가 필요한 부분은 client component로 빼두었고, 필요하지 않은 부분은 server component(page.tsx)에 두었습니다. 서버에서 렌더링할 수 있는 부분은 server component에 둠으로써 초기 렌더링이 빨라질 것을 기대합니다.
+ 아직 미완성입니다. (join1 페이지만 완료)

## 💬 리뷰어분들께
- 다른 좋은 방안 있으시면 말씀해주세용 ~

2023-07-08 11:03 UTC, kangju2000 reviewed
LGTM👍

page와 컴포넌트들을 분리하니 확실히 보기 편해졌네용~!!

2023-07-09 02:02 UTC, guesung commented on app/join/step5/InputForm.tsx
> +  };
personality배열에서을 map 할 때 생성되는 index보다 기존`personalityList`에 있던 id가 더 안정적이고 좋을 것 같네요 !

early return을 통해 보다 코드가 깔끔해졌네요. 좋아요 👍 👍

2023-07-09 02:04 UTC, guesung commented on app/join/step1/InputForm.tsx
> +          }
`aftersend`가 이미 존재합니다 😢  

그래서, 보다 직관적으로 네이밍을 수정하였습니다.

'notReadyForSend'(전송할 준비가 안된 상태) | 'readyForSend'(전송 준비가 된 상태) | 'afterSend'(전송 후 상태) 이렇게 3개의 상태로 나누었습니다.

2023-07-09 03:18 UTC, kangju2000 commented on app/join/step2/BottomModal.tsx
> +          }}
이벤트 핸들러가 길어지면 함수로 빼서 관리하는게 좋을 것 같아요!

근데 이 부분은 이렇게 바꿀 수 있을 것 같네용

```suggestion
          onClick={() => {
            setAgreeCheckList((agreeCheckList) =>
              agreeCheckList.map((agree) => ({
                ...agree,
                isAgreed: !agreeCheckList.every((agree) => agree.isAgreed),
              }))
            );
          }}
```

2023-07-09 03:18 UTC, kangju2000 commented on app/join/step2/BottomModal.tsx
> +              );
요런 방법도 있어요😎
```suggestion
              setAgreeCheckList((prev) =>
                prev.map((prevAgree) => ({
                  ...prevAgree,
                  isAgreed:
                    prevAgree.name === agree.name ? !prevAgree.isAgreed : prevAgree.isAgreed,
                }))
              );
```

2023-07-09 14:32 UTC, guesung commented on app/join/step2/BottomModal.tsx
> +          }}
호 함수 하나로 관리 할 수 있군요 ! 

좋아요 함수가 기니, 가독성을 위해서 위에 따로 뺴둘게요 👍

2023-07-09 15:55 UTC, kangju2000 requested changes

2023-07-09 15:55 UTC, kangju2000 commented on app/join/step2/BottomModal.tsx
> +          }}
이부분 수정 아직 안된것 같아요! 수정 부탁드립니당

2023-07-10 00:55 UTC, guesung commented on app/join/step2/BottomModal.tsx
> +          }}
push를 안했네요, push 완료했습니다 😄

2023-07-10 05:30 UTC, kangju2000 approved these changes

2023-07-10 05:31 UTC, merged